### ISSUE TITLE
Save Info Does Not Work In Realeases

### ISSUE THREAD

**Issue by davidhaw** [davidhaw/FIREcalc#3]
Save info Works When Ran In Eclipse but not in the .dmg release file. This is probably due to compression breaking the db and will probably be fixed by making the db in a outside folder.

**Comment by davidhaw** [comment]
For some reason this has also broken in the source code and not only the .dmg 
The error given is: [SQLITE_ERROR] SQL error or missing database (no such table: earning)
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at application.DBuser.getEarnings(DBuser.java:71)
	at application.Main$3.handle(Main.java:178)
	at application.Main$3.handle(Main.java:1
